### PR TITLE
Fix Loop contains  which contained a missing negation and add test cases.

### LINKED ISSUE #77: Porting bug
Hello there, 

Thanks for implementing S2 in golang!

We found what seemed to be a small porting issue in Loop.go
We noticed that `Loop.Contains(o *Loop)` returns false sometimes when `o` is properly contained. We traced this issue to  [hasCrossingRelation()](https://github.com/golang/geo/blob/740aa86cb551d6388f5cf4a8f39568d52fac6ed7/s2/loop.go#L1620). 
This function doesn't share the same logical control flow with the [original c++ version](https://github.com/google/s2geometry/blob/20ea540d81f4575a3fc0aea585aac611bcd03ede/src/s2/s2loop.cc#L944).

In the go version, currently it returns `false` when the crossing target for `A` is satisfied. We believe it should return `false` when the crossing target is _not_ satisfied. 
So [this line](https://github.com/golang/geo/blob/740aa86cb551d6388f5cf4a8f39568d52fac6ed7/s2/loop.go#L1631) might need a **not** operator at the beginning so it looks like this:
```go
 if !containsCenterMatches(aClipped, l.aCrossingTarget) {...}
 ```

### LINKED ISSUE #78: Bug on Polygon Contains (linked to https://github.com/golang/geo/issues/77 ?)
Hello There,

we noticed that `Contains` method returns `false` sometimes.

Ex: https://play.golang.org/p/WqDx36fG4rG
```
package main

import (
	"fmt"
	"github.com/golang/geo/s2"
)

func main() {
	polygon := s2.PolygonFromLoops([]*s2.Loop{
		s2.LoopFromPoints([]s2.Point{
			s2.PointFromLatLng(s2.LatLngFromDegrees(-38.0, -135.0)),
			s2.PointFromLatLng(s2.LatLngFromDegrees(-38.0, 149.0)),
			s2.PointFromLatLng(s2.LatLngFromDegrees(77.0, 149.0)),
			s2.PointFromLatLng(s2.LatLngFromDegrees(77.0, -135.0)),
			s2.PointFromLatLng(s2.LatLngFromDegrees(-38.0, -135.0)),
		}),
	})
	
	tile := s2.PolygonFromLoops([]*s2.Loop{
		s2.LoopFromPoints([]s2.Point{
			s2.PointFromLatLng(s2.LatLngFromDegrees(37.99616267972809, 13.007812500000002)),
			s2.PointFromLatLng(s2.LatLngFromDegrees(37.99616267972809, 13.359375000000002)),
			s2.PointFromLatLng(s2.LatLngFromDegrees(38.272819658516866, 13.359375000000002)),
			s2.PointFromLatLng(s2.LatLngFromDegrees(38.272819658516866, 13.007812500000002)),
			s2.PointFromLatLng(s2.LatLngFromDegrees(37.99616267972809, 13.007812500000002)),
		}),
	})
	
	// +0.2 lat +0.2 lon
	tileExtended :=  s2.PolygonFromLoops([]*s2.Loop{
		s2.LoopFromPoints([]s2.Point{
			s2.PointFromLatLng(s2.LatLngFromDegrees(37.99616267972809, 13.007812500000002)),
			s2.PointFromLatLng(s2.LatLngFromDegrees(37.99616267972809, 13.559375000000002)),
			s2.PointFromLatLng(s2.LatLngFromDegrees(38.472819658516866, 13.559375000000002)),
			s2.PointFromLatLng(s2.LatLngFromDegrees(38.472819658516866, 13.007812500000002)),
			s2.PointFromLatLng(s2.LatLngFromDegrees(37.99616267972809, 13.007812500000002)),
		}),
	})
	
	fmt.Println(polygon.Contains(tile))
	fmt.Println(polygon.Contains(tileExtended))
}
```

Returns

```
false
true

Program exited.
```

However, all these geometries (tile & tileExtended) are contained in polygon.

Maybe, this might be linked to https://github.com/golang/geo/issues/77

### PR DESCRIPTION
**Pull request by rsned**
Loop's hasCrossingRelation() had the wrong condition on one branch.  This has been resolved and test cases added ensuring it was fixed.

Fix #77 
Fix #78

### CODE REVIEW

File: s2/loop_test.go [hunk 1]
```diff
@@ -1332,6 +1357,18 @@ func TestLoopRelations(t *testing.T) {
 			contains:   true,
 			sharedEdge: true,
 		},
+		// https://github.com/golang/geo/issues/77 and 78
+		// These cases failed prior to this fix.
```
Comment (alan-strohm) [inline s2/loop_test.go:1361]: Remove this comment ("this fix" means the pull request, not the file).  I'd suggest a different comment. Something like:
// Cases below here prevent regressions of bugs which previously appeared in the golang version
// and  which are missing test coverage in the C++ codebase.

File: s2/loop.go [hunk 2]
```diff
@@ -1612,12 +1612,12 @@ func (l *loopCrosser) hasCrossing(ai, bi *rangeIterator) bool {
...
-// containsCenterMatches reports if the clippedShapes containsCenter boolean corresponds
-// to the crossing target type given. (This is to work around C++ allowing false == 0,
-// true == 1 type implicit conversions and comparisons)
-func containsCenterMatches(a *clippedShape, target crossingTarget) bool {
-	return (!a.containsCenter && target == crossingTargetDontCross) ||
-		(a.containsCenter && target == crossingTargetCross)
+// containsCenterMatches reports if the clippedShapes containsCenter boolean
+// corresponds to the crossing target type given. (This is to work around C++
+// allowing false == 0, true == 1 type implicit conversions and comparisons)
+func containsCenterMatches(a bool, target crossingTarget) bool {
```
Comment (alan-strohm) [inline s2/loop.go:1618]: Why not make a  `*rangeIterator`?  That way you can ensure that the boolean means what you intend it to mean.  Alternatively, consider renaming `a` to `containsCenter`.

File: s2/loop.go [hunk 3]
```diff
@@ -1701,16 +1702,16 @@ func hasCrossingRelation(a, b *Loop, relation loopRelation) bool {
...
-					containsCenterMatches(bClipped, ab.bCrossingTarget) {
+				// The A and B cells are the same. Since the two
+				// cells have the same center point P, check
+				// whether P satisfies the crossing targets.
+				if containsCenterMatches(ai.containsCenter(), ab.aCrossingTarget) &&
+					containsCenterMatches(bi.containsCenter(), ab.bCrossingTarget) {
 					return true
 				}
 				// Otherwise test all the edge crossings directly.
+				aClipped := ai.it.IndexCell().shapes[0]
```
Comment (alan-strohm) [inline s2/loop.go:1713]: Why not use your new ai/bi.clipped() function?

**Comment by panmari** [comment]
@rsned do you need help with addressing the comments? Anything I can assist with?

File: s2/loop_test.go (hunk 1 above)
Comment (rsned) [reply s2/loop_test.go:1361]: Updated.

File: s2/loop.go (hunk 3 above)
Comment (rsned) [reply s2/loop.go:1713]: Done

File: s2/loop.go (hunk 2 above)
Comment (rsned) [reply s2/loop.go:1618]: renamed to containsCenter

**Comment by rsned** [comment]
Sorry, I missed seeing the notification last week of your comments.
